Repository saltechco/PuyaKhan, pull requests merged in 2025-07, with the labels that each got.

#2 Refactor: Improve app settings management and code readability
  app/src/main/java/ir/saltech/puyakhan/data/model/App.kt
  app/src/main/java/ir/saltech/puyakhan/data/receiver/OtpSmsReceiver.kt
  app/src/main/java/ir/saltech/puyakhan/data/util/ToolFunctions.kt
  app/src/main/java/ir/saltech/puyakhan/ui/theme/Symbols.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/activity/BackgroundActivity.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/activity/MainActivity.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/component/adapter/OtpCodesViewAdapter.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/model/OtpCodesVM.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/page/SettingsView.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/window/SelectOtpWindow.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement

#1 Merge Feature Secure OTP Storage: Securing saving otp codes via keystore and protobuf
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/ir/saltech/puyakhan/data/datastore/KeystoreManager.kt
  app/src/main/java/ir/saltech/puyakhan/data/datastore/OtpCodeSerializer.kt
  app/src/main/java/ir/saltech/puyakhan/data/datastore/OtpDataStore.kt
  app/src/main/java/ir/saltech/puyakhan/data/model/App.kt
  app/src/main/java/ir/saltech/puyakhan/data/model/OtpCode.kt
  app/src/main/java/ir/saltech/puyakhan/data/receiver/OtpSmsReceiver.kt
  app/src/main/java/ir/saltech/puyakhan/data/util/OtpProcessor.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/activity/MainActivity.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/component/adapter/OtpCodesViewAdapter.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/component/compose/Components.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/model/OtpCodesVM.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/page/SettingsView.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/window/SelectOtpWindow.kt
  app/src/main/proto/otp_code.proto
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
  gradlew
Labels: enhancement

#3 Refactor: Implement Parcelable for App.Settings and App.WindowPosition
  app/build.gradle.kts
  app/src/main/java/ir/saltech/puyakhan/data/model/App.kt
  app/src/main/java/ir/saltech/puyakhan/data/receiver/OtpSmsReceiver.kt
  app/src/main/java/ir/saltech/puyakhan/data/service/SelectOtpService.kt
  app/src/main/java/ir/saltech/puyakhan/data/util/ToolFunctions.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/activity/MainActivity.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/component/adapter/OtpCodesViewAdapter.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/component/compose/Components.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/page/SettingsView.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/window/SelectOtpWindow.kt
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement

#5 feat: Fixed SelectWindow singleton; Fixed SelectWindow repeated showing; Updated fetching appSettings and otpCodes mechanism
  app/src/androidTest/java/ir/saltech/puyakhan/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/ir/saltech/puyakhan/ApplicationLoader.kt
  app/src/main/java/ir/saltech/puyakhan/data/model/OtpModels.kt
  app/src/main/java/ir/saltech/puyakhan/data/model/OtpSms.kt
  app/src/main/java/ir/saltech/puyakhan/data/receiver/OtpSmsReceiver.kt
  app/src/main/java/ir/saltech/puyakhan/data/service/SelectOtpService.kt
  app/src/main/java/ir/saltech/puyakhan/data/util/OtpProcessor.kt
  app/src/main/java/ir/saltech/puyakhan/data/util/OtpSmsHandler.kt
  app/src/main/java/ir/saltech/puyakhan/data/util/ToolFunctions.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/activity/BackgroundActivity.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/activity/MainActivity.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/component/adapter/OtpCodesViewAdapter.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/page/SettingsView.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/window/SelectOtpWindow.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/ir/saltech/puyakhan/ExampleUnitTest.kt
Labels: bug, enhancement

#7 feat: Add Bug Report feature for OtpCodes; and Notifications are optimized
  app/src/main/AndroidManifest.xml
  app/src/main/java/ir/saltech/puyakhan/ApplicationLoader.kt
  app/src/main/java/ir/saltech/puyakhan/data/datastore/OtpCodeSerializer.kt
  app/src/main/java/ir/saltech/puyakhan/data/model/OtpModels.kt
  app/src/main/java/ir/saltech/puyakhan/data/receiver/OtpSmsReceiver.kt
  app/src/main/java/ir/saltech/puyakhan/data/util/OtpParser.kt
  app/src/main/java/ir/saltech/puyakhan/data/util/OtpProcessor.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/activity/BackgroundActivity.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/activity/MainActivity.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/component/adapter/OtpCodesViewAdapter.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/component/compose/Components.kt
  app/src/main/proto/otp_code.proto
  app/src/main/res/drawable/otp_action_delete.xml
  app/src/main/res/drawable/rounded_bug_report_24.xml
  app/src/main/res/layout/layout_template_otp.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#8 Fixed minor bugs: There was several minor bugs for processing OTP; Fixed bugs in UI
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/ir/saltech/puyakhan/ApplicationLoader.kt
  app/src/main/java/ir/saltech/puyakhan/data/datastore/OtpCodeSerializer.kt
  app/src/main/java/ir/saltech/puyakhan/data/model/OtpModels.kt
  app/src/main/java/ir/saltech/puyakhan/data/receiver/OtpSmsReceiver.kt
  app/src/main/java/ir/saltech/puyakhan/data/util/OtpProcessor.kt
  app/src/main/java/ir/saltech/puyakhan/data/util/OtpSmsHandler.kt
  app/src/main/java/ir/saltech/puyakhan/data/util/ToolFunctions.kt
  app/src/main/java/ir/saltech/puyakhan/data/util/XiaomiUtilities.java
  app/src/main/java/ir/saltech/puyakhan/ui/theme/Type.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/activity/BackgroundActivity.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/activity/MainActivity.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/component/adapter/OtpCodesViewAdapter.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/component/compose/Components.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/model/OtpCodesVM.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/page/SettingsView.kt
  app/src/main/java/ir/saltech/puyakhan/ui/view/window/SelectOtpWindow.kt
  app/src/main/proto/otp_code.proto
  app/src/main/res/drawable/otp_action_bug_report.xml
  app/src/main/res/font/vazirmatn_light.ttf
  app/src/main/res/font/vazirmatn_regular.ttf
  app/src/main/res/values/strings.xml
Labels: bug
